services:
  minion:
    build: .
    environment:
      CNM_CONFIG: /config/config.yml
      CNM_MODE: minion
      CNM_NODE_NAME: cozy-minion
      CNM_HOST_ROOT: /host
    ports:
      - "8000:8000"
    volumes:
      - ./config.example.yml:/config/config.yml:ro
      - /etc/hostname:/host/etc/hostname:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/wireguard:/host/etc/wireguard:ro
      - /root/wireguard/clients:/host/wireguard/clients:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
